### ISSUE TITLE
Calling initialize in thread-attach vs just process-attach

### ISSUE THREAD

**Issue by arithex** [Havner/np-wrapper#1]
https://github.com/Havner/np-wrapper/blob/f1814bee4423bb8c3cfbb7d6fb9114e22708fd14/dllmain.c#L247

I think you only need to do the initialize() in DLL_PROCESS_ATTACH .. not DLL_THREAD_ATTACH .. right?

**Comment by Havner** [comment]
Yeah, probably, I completely ignored that part after initial look and I don't really know this stuff work in Windows. Might actually be the reason why I get so many initializations. I though this function will get called only on implicit LoadLibrary(Ex), but might not be the case.

**Comment by Havner** [comment]
Yeah, that solved the ~50 initializations I had. So all is fine on your side, mea culpa :-)

**Comment by Havner** [comment]
Fixed
