### ISSUE TITLE
MSVC runtime - static link vs DLL

### ISSUE THREAD

**Issue by arithex** [Havner/np-wrapper#2]
https://github.com/Havner/np-wrapper/blob/f1814bee4423bb8c3cfbb7d6fb9114e22708fd14/dllmain.c#L5

Not sure why this would be the case -- it might be something I should investigate?

BMS statically links the MSVC / std runtime libs.

My memory could be wrong, but I think VS project default is to use the DLL based std libs -- which could potentially conflict with std libs brought in by another DLL..   I expect to see 

```<RuntimeLibrary>MultiThreaded</RuntimeLibrary>```
/
```<RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>```

in the vcxproj file, to indicate static-link to the CRT libs.   (I think there's also a corresponding preprocessor macro to define?  or maybe the compiler does that automatically..  can't remember.)

https://learn.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-170

**Comment by Havner** [comment]
Haven't really debugged this. I initially tried C allocators (malloc/free) for the main struct with function pointers and I got heap corruption crashes. After that I decided to really do this the simplest possible way, pure C, no stdlib usage if I can help it (except some stdio) not to conflict with anything.

I haven't tried C++ allocators.

In any case if you use two allocators in the same memory they might conflict. And not knowing what is actually going on in BMS code I decided to limit any potential conflicts. I'm also not really proficient in Windows programming. I mostly do Linux and some embedded.

**Comment by arithex** [comment]
In theory it should be fine .. the windows world is composed of dozens/hundreds of DLLs made by different teams and different companies, all playing nice together [citation-needed].

Every "module" (exe or dll) has its own private C-runtime .. its own heap, for malloc/free and new/delete.   In theory it shouldn't even matter if static-linking the C-runtime into your module, or dynamic linking..  MS does a good job of rev'ing the DLL name if there are incompatible changes.  (so eg. you see things like MSVCR140.dll vs MSVCR170.dll)

I think only a handful of oldschool C runtime functions like strtok, that imply global/static state, are problematic, these days.

Maybe C-runtime stuff that uses thread-local storage .. like RTTI?  Not sure.   I'll let you know what I discover.  I feel like maybe I'll learn something..

**Comment by arithex** [comment]
Ah, it's because you're doing all this initialization within scope of DllMain.  That's a no-no.

https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices

Calling malloc/free (or new/delete) would probably be ok if static-linking the C-runtime -- the crux of the problem is, code that would cause loading of C-runtime DLLs, within DllMain -- but it's worth avoiding any code flow that has that lingering risk.

So..  you should definitely not call LoadLibrary* functions within there either.

FIX:  don't call initialize() within DllMain.   Adopt a lazy-init strategy, in all the exported NP_* methods.

Bit of a pain, but that's Win32 for you.

**Comment by Havner** [comment]
Good catch. Come to think of it this is the first DLL I've ever written in my life from scratch ;-) I don't know this stuff.

**Comment by Havner** [comment]
Out of curiosity I've checked the D3D11 BMS wrapper (dedi server). They create threads and load libraries in DllMain.

**Comment by Havner** [comment]
I've moved to lazy initialization.
