### ISSUE TITLE
I don't think fopen will create this directory

### ISSUE THREAD

**Issue by arithex** [Havner/np-wrapper#3]
https://github.com/Havner/np-wrapper/blob/cf380a6d9026d834ec7f473d561d5b696b505bae/log.h#L5

I recommend `%Temp%`

**Comment by Havner** [comment]
It surely won’t create it. This code is only in debug build. I wrote in the readme that this path needs to be adjusted when someone builds the debug version. I didn’t bother with env as the release builds don’t use it.

**Comment by Havner** [comment]
I'll probably do a generic debug build as forums show that first user has an issue. So I'll need to provide something that logs.

**Comment by Havner** [comment]
I did logging to a file path taken from env.
